---
apiVersion: apps/v1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: somepod
  labels:
    app: somepod
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: somepod
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: quay.io/stefanprodan/podinfo:3.0.0
        ports:
        - containerPort: 3000
